## Medida de similaridade dos textos

In [1]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
#Bag of words
texto_inicial = 'Olha como é fácil fazer esse picole em casa! Uma receita deliciosa pra curtir o melhor picole até no inverno'
texto_comparativo = 'Os melhores picole sao os que já compramos nos postos perto de casa pois sao mais faceis de fazer'

### Quantidde N_gramas
- Unigrama
n = 1
- Bigrama
n = 2
- Trigrama
n = 3

In [27]:
#qtd N_gramas
n =1
#Instanciando no analyzer ignoramos artigos pois usamos o parametro word
vectorizer = CountVectorizer(analyzer = 'word',ngram_range=(n, n),binary=True)

#criando dicionario
X = vectorizer.fit([texto_inicial,texto_comparativo]).vocabulary_
print(X)

{'olha': 19, 'como': 2, 'fácil': 11, 'fazer': 10, 'esse': 8, 'picole': 22, 'em': 7, 'casa': 1, 'uma': 29, 'receita': 27, 'deliciosa': 6, 'pra': 25, 'curtir': 4, 'melhor': 15, 'até': 0, 'no': 17, 'inverno': 12, 'os': 20, 'melhores': 16, 'sao': 28, 'que': 26, 'já': 13, 'compramos': 3, 'nos': 18, 'postos': 24, 'perto': 21, 'de': 5, 'pois': 23, 'mais': 14, 'faceis': 9}


### Array dos N_gramas

In [29]:
n =1

vectorizer = CountVectorizer(analyzer = 'word',ngram_range=(n, n),binary=True)

X = vectorizer.fit_transform([texto_inicial,texto_comparativo])

X1 = vectorizer.fit([texto_inicial,texto_comparativo]).vocabulary_

n_g_array = X.toarray()

print('Valor de n-grams \n\n',n_g_array)
print('-'*70)
print('Dicionario dos n-grams \n\n',X1)

Valor de n-grams 

 [[1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 1 0 1 0 1 0 0 1 0 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 0 0 1 1 0 0 1 1 0 1 0 1 0 1 1 1 1 1 0 1 0 1 0]]
----------------------------------------------------------------------
Dicionario dos n-grams 

 {'olha': 19, 'como': 2, 'fácil': 11, 'fazer': 10, 'esse': 8, 'picole': 22, 'em': 7, 'casa': 1, 'uma': 29, 'receita': 27, 'deliciosa': 6, 'pra': 25, 'curtir': 4, 'melhor': 15, 'até': 0, 'no': 17, 'inverno': 12, 'os': 20, 'melhores': 16, 'sao': 28, 'que': 26, 'já': 13, 'compramos': 3, 'nos': 18, 'postos': 24, 'perto': 21, 'de': 5, 'pois': 23, 'mais': 14, 'faceis': 9}


## Containment

In [11]:
X

<2x30 sparse matrix of type '<class 'numpy.int64'>'
	with 33 stored elements in Compressed Sparse Row format>

In [12]:
X.toarray()

array([[1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
        2, 0, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 2, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 2, 1,
        1, 1, 1, 0, 1, 0, 2, 0]], dtype=int64)

In [30]:
interesecao = np.amin(X.toarray(),axis=0)
interesecao

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [31]:
contagem = np.sum(interesecao)
contagem

3

In [32]:
index_1 = 0
cont_index = np.sum(X.toarray()[index_1])
cont_index

17

In [33]:
contagem/cont_index

0.17647058823529413

In [34]:
print('O grau de similiridade desse texto é de {:.2%}'.format(contagem/cont_index))

O grau de similiridade desse texto é de 17.65%
